### PR TITLE
Allow ApiQueries to return a Serializable state from which the origin…

### PR DESCRIPTION
**Pull request by dmfs**
…al ApiQuery can be recreated. Implements #34

### CODE REVIEW

**Comment by dmfs** [comment]
@lemonboston there are a few minor issues to fix, but it should show the idea. Please comment.

**Comment by lemonboston** [comment]
The idea looks nice to me.

Could the interfaces work more generally as well? Like:
```
interface Restorable<T>
{
    State<T> state()
}

interface State<T> extends Serializable
{
    T restored();
}

interface ApiQuery<T> extends Restorable<ApiQuery<T>>
```

**Comment by dmfs** [comment]
This would only work for simple objects and is not as universal as it might seem. "Restoring" an object may require additional non-serializable parameters. For instance, in Android it might be necessary to pass a `Context` to recreate the object. In oauth2-essentials we need an `OAuth2Client` in order to restore `OAtuh2Grant` instances.

So the `State` interface sort of depends on the type of the class that is serialized.

**Comment by lemonboston** [comment]
I see. Still with the above they would be kind of the same as the Parcelable serialization design.

```
interface State<T> extends Serializable
{
    T restored();
}

interface Box<T> extends Parcelable
{
    T content()
}
```
So I wonder whether it would make sense to use it like that. And where custom paramaters are need, that would be a different thing.

**Comment by dmfs** [comment]
I've generalized state as suggested. I didn't introduce a `Restorable` yet, I suggest we get back to that when we actually need it.
Please have another look.

**Comment by lemonboston** [comment]
It looks good, looks like the correct move for me, too, at this point.
(I don't have any more comments.)

**Pull request merged**
