### PR TITLE
Support for GET Categories API request. #31

### PR DESCRIPTION
**Pull request by lemonboston**
@dmfs Could you please have a first look before I do any testing to check if this looks good in general?

### CODE REVIEW

**Comment by lemonboston** [comment]
I've functional tested it in the SDK and it works. I leave the finalization (javadocs, unit tests) after your first review.

I guess the question is the Category model:
```java
public interface Category
{
    Uri name();
    CharSequence label();
}
```
For the label, I thought using `CharSequence` instead of `String` may give more flexibility in the SDK even though `JsonCategory` will always use `String`.
For the `name`, I am not sure about the detailed plans for the categories system, so I am not sure what is the best model. Should we start to represent hierarchy like main category, subcategory here or not. Or how much the uri structure can be made useful.

So for example these 2 categories:
```json
   {
      "name":"http://schedjoules.com/categories/music/indie",
      "label":"Indie",
      "filterable":true
   },
   {
      "name":"http://schedjoules.com/categories/music",
      "label":"Music",
      "filterable":true
   },
```
Are we going to show the subcategory labels right away or only the main ones for now?
If we only start with main ones, or in any way we would like to take it simple first, maybe we can just use `String` instead of `Uri`. Because maybe `Uri` is not the best representation of 'category hierarchical id', maybe we can return something specific there already. But if it doesn't matter now, we can go with `String`, so we can use that easily for map key as well.

**Comment by lemonboston** [comment]
Just dumping a sample Event json here, so we can see how category is used there to see how we can possibly use the same model for both:
```json
...
"links": [
                                                             {
                                                                 "rel": "http:\/\/schedjoules.com\/rel\/banner",
                                                                 "type": "image\/png",
                                                                 "href": "https:\/\/s1.ticketm.net\/dam\/a\/7af\/cb3c12f0-5a88-49bc-ab45-85f303d967af_25991_TABLET_LANDSCAPE_LARGE_16_9.jpg",
                                                                 "properties": {
                                                                     "https:\/\/schedjoules.com\/prop\/width": "768",
                                                                     "https:\/\/schedjoules.com\/prop\/height": "512"
                                                                 }
                                                             },
                                                             {
                                                                 "rel": "http:\/\/schedjoules.com\/rel\/thumbnail",
                                                                 "type": "image\/png",
                                                                 "href": "https:\/\/s1.ticketm.net\/dam\/a\/7af\/cb3c12f0-5a88-49bc-ab45-85f303d967af_25991_TABLET_LANDSCAPE_LARGE_16_9.jpg",
                                                                 "properties": {
                                                                     "https:\/\/schedjoules.com\/prop\/width": "128",
                                                                     "https:\/\/schedjoules.com\/prop\/height": "128"
                                                                 }
                                                             },
                                                             {
                                                                 "rel": "http:\/\/schedjoules.com\/rel\/category",
                                                                 "href": "https:\/\/schedjoules.com\/categories\/music"
                                                             },
                                                             {
                                                                 "rel": "http:\/\/schedjoules.com\/rel\/category",
                                                                 "href": "https:\/\/schedjoules.com\/categories\/music\/blues"
                                                             }
                                                         ]
...
```

**Comment by dmfs** [comment]
In general it looks good but why did you choose to put this into a separate module? If we need something of this in the event discovery module we'll get a circular dependency. I think this should go to the event discovery module. We can factor this out later on.

**Comment by lemonboston** [comment]
I've created the module to do it similarly as actions module but I see that it's probably not needed, so I've moved the files now to the `eventsdiscovery` module.

Added the javadocs and a test, ready for final review.

**Pull request merged**
